# Generated by Django 6.0.3 on 2026-04-01 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='traiteur',
            name='annees_experience',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='traiteur',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='traiteurs/'),
        ),
    ]
