# Generated by Django 6.0.3 on 2026-04-02 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_traiteur_annees_experience_alter_traiteur_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traiteur',
            name='est_actif',
            field=models.BooleanField(default=False),
        ),
    ]
