# Generated by Django 6.0.3 on 2026-04-02 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_traiteur_est_actif'),
    ]

    operations = [
        migrations.AddField(
            model_name='traiteur',
            name='langues',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
