# Generated by Django 6.0.3 on 2026-04-02 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_traiteur_langues'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traiteur',
            name='langues',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='traiteur',
            name='specialites',
            field=models.CharField(default='', max_length=255),
        ),
    ]
