# Generated by Django 6.0.3 on 2026-04-02 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_alter_traiteur_langues_alter_traiteur_specialites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traiteur',
            name='specialites',
            field=models.CharField(max_length=255),
        ),
    ]
